@echo off
echo Starting YBG Manufacturing ERP...
echo.
echo [1/2] Launching Backend in a new window...
start cmd /k "cd backend && npm run dev"
echo [2/2] Launching Frontend...
cd frontend && npm run dev
pause
